fileObj=open("login3.txt","w")
fileObj.write("ictak\n")
    #fileObj.close()
fileObj=open("login3.txt","a")
fileObj.write("1234")
username=input("Enter the username")
password=input("Enter the password")
fileObj=open("login3.txt","r")
Uname=fileObj.readline()
Pass=fileObj.readline()
print(username)
print(password)
print(Uname)
print(Pass)
Uname=Uname.rstrip("\n")
if username==Uname and password==Pass:
    print("Successeful login")
else:
    print("Unsuccssesful")